### ISSUE TITLE
HMAC link bulundu, yeniden deneniyor..

### ISSUE THREAD

**Issue by b3rkaydem1r** [sh4dowb/puhutv-downloader#2]
Bölüm ID alınıyor..
Bölüm ID: 4849
Video listesi alınıyor..
HMAC link bulundu, yeniden deneniyor..
Video listesi alınıyor..
HMAC link bulundu, yeniden deneniyor..
Video listesi alınıyor..
HMAC link bulundu, yeniden deneniyor..
Video listesi alınıyor..
HMAC link bulundu, yeniden deneniyor..
Video listesi alınıyor..
HMAC link bulundu, yeniden deneniyor..
Video listesi alınıyor..
HMAC link bulundu, yeniden deneniyor..
Video listesi alınıyor..
HMAC link bulundu, yeniden deneniyor..
Video listesi alınıyor..
HMAC link bulundu, yeniden deneniyor..
Video listesi alınıyor..
HMAC link bulundu, yeniden deneniyor..
Video listesi alınıyor..
HMAC link bulundu, yeniden deneniyor..
Böyle bir yazıyla karşılaştım. Verdiğim link; https://puhutv.com/yalanci-yarim-44-bolum-izle

**Comment by sh4dowb** [comment]
Bende sorun yok şuanda.

```Bölüm ID alınıyor..
Bölüm ID: 4849
Video listesi alınıyor..

144p
240p
360p
480p
720p
1080p```

Sayfayı yenilemeyi denedin mi?

**Comment by b3rkaydem1r** [comment]
Evet teşekkürler ertesi gün denediğimde düzelmişti.
