### ISSUE TITLE
405 Not Allowed

### ISSUE THREAD

**Issue by TurboProgramming** [sh4dowb/puhutv-downloader#3]
Selam,
Yazılımınızı kullanarak puhutv'den indirme yaparken 405 Not Allowed hatasını aldım.

İndirmek istediğim içeriğin bağlantısı: https://puhutv.com/sahsiyet-1-bolum-izle

Hatanın ekran görüntüsü:

![screenshot-2018-4-25 405 not allowed](https://user-images.githubusercontent.com/17576065/39214510-5b746ee0-481d-11e8-914a-64540c3bd753.png)

**Comment by sh4dowb** [comment]
Demo üzerinde sorun yok. Demodan mı deniyorsunuz, yoksa kendi sunucunuzda mı?
Bir URL'ye yönlendirme yapıyor sanki. Normalde yönlendirme yapmadan, AJAX ile çekip demo sayfasında göstermesi lazım.

![image](https://user-images.githubusercontent.com/12783710/39252701-ee655192-48ae-11e8-8f1c-1e9ed7e4cca2.png)

**Comment by TurboProgramming** [comment]
Demo üzerinden deniyorum.

**Comment by TurboProgramming** [comment]
Tarayıcı fark eder mi? Firefox kullanıcısıyım.

**Comment by TurboProgramming** [comment]
![](https://i.imgur.com/wlMKJb9.png)

Mobil Chrome ile sonuç böyle oluyor.

**Comment by TurboProgramming** [comment]
İkinci kez çalıştı. 

Birinci denemede olmuyor.

405 Not Allowed hatası çıktığında sayfa sanki sadece yenileniyor gibi. Aynı link.

**Comment by sh4dowb** [comment]
405 hatası devam mı ediyor?

**Comment by TurboProgramming** [comment]
Tamamdır, ilk denemede çalıştı.
