### ISSUE TITLE
puhutv-downloader seems to be not working in 2019

### ISSUE THREAD

**Issue by gyufa** [sh4dowb/puhutv-downloader#8]
Hi, 

In 2018 the code worked fine, but from 2019 it seems to be not. 

Log:
Fetching episode ID...
Episode ID: xxxxxx  //any valid episode ID
Fetching video list...
HMAC video link found, retrying...
HMAC video link found, retrying...
...
Maximum retry count exceeded. Please try again.

I wonder if it is possible to repair.

Many thanks

**Comment by sh4dowb** [comment]
Hey! Yeah it seems their backend has updated. I think it's possible to fix, I'm working on it. Thanks for reporting the issue

**Comment by sh4dowb** [comment]
It should be fixed now!

**Comment by gyufa** [comment]
It is working now.
Çok teşekkür ederim!

Note: Downloading 1080p videos is not possible, message (e.g.):
An error occurred while processing your request.
Reference #172.b5700617.1547577091.49073c2

**Comment by sh4dowb** [comment]
Yes, I don't think there's anything I can do about it, but it might work for some videos so I left the option there

**Comment by gyufa** [comment]
Selam, haber olsun:
hidemyreferrer.com discontinued the service.
Pazar kapandi...

**Comment by sh4dowb** [comment]
Merhaba, teşekkürler bilgi için şimdi güncelliyorum.

**Comment by gyufa** [comment]
Works smoothly. Hızlı düzeltme için çok sağol.

**Comment by gyufa** [comment]
...yani, güncelleştirme için.
